-- +goose Up
-- +goose StatementBegin

-- Seed the dev admin account.
-- Credentials: email=admin@soapbox.dev, password=admin123 (bcrypt cost 10)
--
-- Guarded by a runtime check: only executes when current_setting('app.env')
-- is 'development' (the default). Production deployments must set this to
-- 'production' to skip seeding.
--
-- The INSERT ... ON CONFLICT DO NOTHING guards against re-runs.

DO $$
DECLARE
    v_env  text;
    v_user_id uuid := 'a0000000-0000-7000-8000-000000000001';
BEGIN
    -- Check environment. Default to 'development' if not set.
    BEGIN
        v_env := current_setting('app.env');
    EXCEPTION WHEN undefined_object THEN
        v_env := 'development';
    END;

    IF v_env <> 'development' THEN
        RAISE NOTICE '002_seed_admin: skipping admin seed (app.env=%)', v_env;
        RETURN;
    END IF;

    -- Create the profile for the admin user.
    INSERT INTO users.profiles (id, username, display_name, bio, verified)
    VALUES (v_user_id, 'admin', 'Admin', 'Soapbox administrator', true)
    ON CONFLICT DO NOTHING;

    -- Resolve the actual id in case the profile already existed.
    SELECT id INTO v_user_id
    FROM users.profiles
    WHERE lower(username) = 'admin';

    -- Attach email/password credentials.
    -- Hash generated by Go's golang.org/x/crypto/bcrypt at DefaultCost (10).
    INSERT INTO users.credentials (id, user_id, email, password_hash)
    VALUES (
        'a0000000-0000-7000-8000-000000000002',
        v_user_id,
        'admin@soapbox.dev',
        '$2a$10$/QjsfM9VeDP9heFtTTnZOu1QDiaF7V.JbmH80wf8LJHWWiBN9rAha'
    )
    ON CONFLICT (user_id) DO NOTHING;

    -- Grant admin role.
    INSERT INTO users.roles (id, user_id, role)
    VALUES ('a0000000-0000-7000-8000-000000000003', v_user_id, 'admin')
    ON CONFLICT (user_id) DO NOTHING;
END;
$$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DO $$
DECLARE
    v_user_id uuid;
BEGIN
    SELECT id INTO v_user_id
    FROM users.profiles
    WHERE lower(username) = 'admin';

    IF v_user_id IS NOT NULL THEN
        -- Cascade handles credentials, sessions, oauth_links, roles, follows.
        DELETE FROM users.profiles WHERE id = v_user_id;
    END IF;
END;
$$;
-- +goose StatementEnd
