linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gofmt

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-dirs:
    - vendor
    - tmp
    - web
    - node_modules
